import { useState } from 'react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Checkbox } from './ui/checkbox';
import { createClient } from '../utils/supabase/client';

interface ContractScreenProps {
  userId: string;
  onComplete: () => void;
}

const CONTRACT_TEXT = `INDEPENDENT CONTRACTOR AGREEMENT

This Independent Contractor Agreement (the "Agreement") is entered into as of the date of electronic signature below (the "Effective Date") by and between Patron Pass Inc., a Delaware corporation ("Company"), and the individual signing below ("Contractor").

WHEREAS, Company operates a membership platform for nightlife venues and hospitality businesses; and

WHEREAS, Contractor desires to provide venue acquisition and relationship management services to Company as an independent contractor;

NOW, THEREFORE, in consideration of the mutual covenants and agreements hereinafter set forth, the parties agree as follows:

1. ENGAGEMENT OF SERVICES
Company hereby engages Contractor to provide venue acquisition, relationship management, and promotional services (the "Services") on an independent contractor basis. Contractor agrees to perform the Services in accordance with Company's guidelines and quality standards.

2. INDEPENDENT CONTRACTOR STATUS
The parties intend that Contractor shall be an independent contractor and not an employee, agent, joint venturer, or partner of Company. Contractor shall have no authority to bind Company in any manner whatsoever. Contractor is solely responsible for all taxes, withholdings, and other statutory obligations.

3. COMPENSATION STRUCTURE
Contractor shall be compensated based on the following structure:
   a) Revenue Share: Contractor shall receive a percentage share of platform fees generated by venues they successfully onboard and activate, subject to tiered commission rates based on performance rank.
   b) Bonuses: Performance-based bonuses as determined by Company for achieving specific milestones.
   c) Payment Terms: Payments shall be made monthly, net 30 days from the end of each calendar month, subject to venue payment receipt.

4. TERM AND TERMINATION
This Agreement shall commence on the Effective Date and continue until terminated by either party upon thirty (30) days' written notice. Company may terminate this Agreement immediately for cause, including but not limited to fraud, misrepresentation, or violation of Company policies.

5. CONFIDENTIALITY
Contractor acknowledges that during the term of this Agreement, Contractor will have access to confidential and proprietary information of Company. Contractor agrees to maintain the confidentiality of such information and not to disclose it to any third party or use it for any purpose other than performing the Services.

6. INTELLECTUAL PROPERTY
All work product, materials, and intellectual property created by Contractor in connection with the Services shall be deemed works made for hire and shall be the sole property of Company. To the extent any such work product does not qualify as a work made for hire, Contractor hereby assigns all right, title, and interest in such work product to Company.

7. NON-SOLICITATION
During the term of this Agreement and for a period of twelve (12) months thereafter, Contractor shall not, directly or indirectly, solicit or attempt to solicit any venue or business that is a client of Company to terminate or reduce its relationship with Company.

8. REPRESENTATIONS AND WARRANTIES
Contractor represents and warrants that:
   a) Contractor has the full right, power, and authority to enter into this Agreement and perform the Services;
   b) The execution and performance of this Agreement will not violate any other agreement to which Contractor is a party;
   c) All information provided to Company is accurate and complete.

9. INDEMNIFICATION
Contractor agrees to indemnify, defend, and hold harmless Company and its officers, directors, employees, and agents from and against any and all claims, damages, liabilities, costs, and expenses arising out of or relating to Contractor's performance of the Services or breach of this Agreement.

10. GENERAL PROVISIONS
This Agreement constitutes the entire agreement between the parties and supersedes all prior agreements and understandings. This Agreement may be amended only by written agreement signed by both parties. This Agreement shall be governed by the laws of the State of Delaware.

BY ELECTRONICALLY SIGNING BELOW, CONTRACTOR ACKNOWLEDGES THAT CONTRACTOR HAS READ THIS AGREEMENT, UNDERSTANDS IT, AND AGREES TO BE BOUND BY ITS TERMS AND CONDITIONS.`;

export function ContractScreen({ userId, onComplete }: ContractScreenProps) {
  const [agreed, setAgreed] = useState(false);
  const [signature, setSignature] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!agreed) {
      setError('You must agree to the terms to continue');
      return;
    }

    if (!signature.trim()) {
      setError('Please type your full legal name');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const supabase = createClient();

      // Insert contract acceptance
      const { error: insertError } = await supabase
        .from('street_contract_acceptances')
        .insert({
          user_id: userId,
          agreement_version: '1.0',
          accepted_at: new Date().toISOString(),
          typed_signature: signature,
          device_info: navigator.userAgent,
        });

      if (insertError) throw insertError;

      // Update user status to active
      const { error: updateError } = await supabase
        .from('street_users')
        .update({ status: 'active' })
        .eq('id', userId);

      if (updateError) throw updateError;

      onComplete();
    } catch (err: any) {
      setError(err.message || 'Failed to accept contract');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#050505]">
      {/* Header */}
      <div className="border-b-4 border-[#F6F2EE] bg-[#151515] px-6 py-4">
        <h3 className="text-[#F6F2EE]">Independent Contractor Agreement</h3>
      </div>

      {/* Contract text */}
      <div className="flex-1 overflow-y-auto px-6 py-6">
        <div className="max-w-2xl mx-auto">
          <div className="p-6 bg-[#151515] border-3 border-[#F6F2EE] mb-6">
            <div className="prose prose-invert max-w-none">
              <pre className="whitespace-pre-wrap text-sm text-[#F6F2EE] leading-relaxed font-sans">
                {CONTRACT_TEXT}
              </pre>
            </div>
          </div>

          {/* Agreement form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="flex items-start gap-3 p-4 bg-[#151515] border-3 border-[#F6F2EE]">
              <Checkbox
                id="agree"
                checked={agreed}
                onCheckedChange={(checked) => setAgreed(checked as boolean)}
                className="mt-1 border-2 border-[#F6F2EE] data-[state=checked]:bg-[#8A4FFF]"
              />
              <Label htmlFor="agree" className="text-[#F6F2EE] cursor-pointer leading-relaxed">
                I have read and agree to the terms of this Independent Contractor Agreement
              </Label>
            </div>

            <div>
              <Label className="text-[#F6F2EE] uppercase tracking-wider text-sm mb-2 block">
                Type your full legal name (this is your signature)
              </Label>
              <Input
                value={signature}
                onChange={(e) => setSignature(e.target.value)}
                required
                className="h-12 bg-[#151515] border-3 border-[#F6F2EE] text-[#F6F2EE]"
                placeholder="Your Full Legal Name"
              />
            </div>

            {error && (
              <div className="p-4 bg-[#FF4444] border-3 border-[#F6F2EE] text-[#F6F2EE]">
                <p className="text-sm">{error}</p>
              </div>
            )}

            <Button
              type="submit"
              disabled={loading || !agreed || !signature.trim()}
              className="w-full h-14 bg-[#8A4FFF] hover:bg-[#7A3FEF] text-[#F6F2EE] border-4 border-[#F6F2EE] uppercase tracking-wider disabled:opacity-50"
            >
              {loading ? 'Processing...' : 'Sign & Continue'}
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
